version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn myProject.wsgi:application --bind 0.0.0.0:8000
    working_dir: /opt/project/app/
    volumes:
      - ./app:/opt/project/app
      - static_volume:/opt/project/app/static
      - media_volume:/opt/project/app/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    # networks:
    #   - front
    #   - back

  db:
    image: postgres:14.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    # networks:
    #   - back

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/opt/project/app/static
      - media_volume:/opt/project/app/media
    ports:
      - "80:80"
    depends_on:
      - app
  #   networks:
  #     - front

volumes:
  db_data:
  static_volume:
  media_volume:

# networks:
#   front:
#     external: false
#   back:
#     external: false
